### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=xeLvn4&redirect_uri=www.51xuecheng.cn

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123


###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzgyNDkwMjIsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjA1ZDczOWNmLTlmODAtNDAzOC05ZjgwLTA4NTNlYjVlNTQyYSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.yN8ii7PTycOFH-PfQt17Eu0xzm_ePHy7J_edunzl8D4

### 访问内容管理服务资源
GET http://localhost:63040/content/course/2

### 携带令牌
GET http://localhost:63040/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzgyNTEwOTAsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjJmODIyMDZlLWVmZGYtNGNhNS04NzEyLThjMDNjMGZkMThiMyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.OTcviPtfb2TAIaNUxOoAdPKSCQTcASr3b1FVK9kW0nQ