### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=xeLvn4&redirect_uri=www.51xuecheng.cn

### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"authType": "password", "username": "admin", "password": "123456"}


###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNDhcIixcIm5hbWVcIjpcIuezu-e7n-euoeeQhuWRmFwiLFwicGVybWlzc2lvbnNcIjpbXSxcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCIxXCIsXCJ1c2VybmFtZVwiOlwiYWRtaW5cIixcInV0eXBlXCI6XCIxMDEwMDNcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc4MjcyNDY0LCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjYxMDg1NmJiLWU0MGItNDQxYi04N2FhLTk2OTM3ODdlYjIwMSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.qVUBlnvqVjlrVw9fsPvwlDF_dUhmI6kMmfnUQxXyIIg

### 访问内容管理服务资源
GET http://localhost:63040/content/course/2

### 携带令牌
GET http://localhost:63040/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNDhcIixcIm5hbWVcIjpcIuezu-e7n-euoeeQhuWRmFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJhZG1pblwiLFwidXR5cGVcIjpcIjEwMTAwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzgyNjMwODYsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiNzU5OTk1MjMtNDJlOC00N2Q3LWJiMzQtZWVjMzI2MDlhZWZmIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.xPsMn78ccVuXDgw46an2REo7m-nmug9GobI4CUdkEjE

### 网关访问内容管理服务资源
GET http://localhost:63010/content/course/2

### 通过网关访问内容管理服务资源
GET http://localhost:63010/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2NzgyNTg4NTgsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjA5NzU4ZTJiLTczNDUtNDdmYy1hOTM0LWQ2M2Y0ZWIzNzJjYyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.1rrR62uDY1FucWCxqyxXLtXmJKD9jKQ9x7GrZEokHQs