### 课程查询接口
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
content-type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

### 课程分类查询
GET {{content_host}}/content/course-category/tree-nodes

### 新增课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "name": "",
  "users": "",
  "tags": "标签",
  "mt": "",
  "st": "1-1-1",
  "grade": "204001",
  "teachmode": "200002",
  "description": "课程介绍",
  "pic": "",
  "charge": "201001",
  "price": 0,
  "originalPrice": "",
  "qq": "15410512",
  "wechat": "weixin",
  "phone": "1351852",
  "validDays": 365
}